spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://localhost:8081
          predicates:
            - Path=/booking/**
        - id: event
          uri: http://localhost:8082
          predicates:
            - Path=/event/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=/ws/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payment/**
        - id: user
          uri: http://localhost:8085
          predicates:
            - Path=/user/**
server:
  port: 8090

jwt:
  secret: SECRETKEY64ASDASDSADASDSADSADASDASDSADASSDASDASDASDASDASDAD
